#!/bin/bash
execPath=${0%/*}
source $execPath/param

newsbeuter

# Start the tmux session for the sender
tmux new-session -d -s $tmuxName
tmux select-pane -t $tmuxName
tmux send-keys "$serverPath/sender &" C-m
